HEADER = ('Montserrat', 18, 'bold')
BUTTON_FONT = ('Arial', 9)
LABEL_FONT = ('Montserrat', 9)
ERROR_FONT = ('Montserrat',9)
LINK_FONT = ('Montserrat',8,'underline')
LISTBOX_FONT = ('Montserrat',9)
HIGHLIGHT_FONT = ('Karma',12)